### ISSUE TITLE
 attn = attn * dis[None, :, :, :] The size of tensor a (4096) must match the size of tensor b (1024) at non-singleton dimension 3

### ISSUE THREAD

**Issue by crissyewang** [xianlin7/ConvFormer#12]
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    main()
  File "train.py", line 97, in main
    output = model(input_image)
  File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 719, in forward
    x = self.transformer(x)  # b c h w -> b c h w
  File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 342, in forward
    x = attn(x) + x
  File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 142, in forward
    attn = attn * dis[None, :, :, :]
RuntimeError: The size of tensor a (4096) must match the size of tensor b (1024) at non-singleton dimension 3

**Comment by xianlin7** [comment]
> Traceback (most recent call last): File "train.py", line 132, in main() File "train.py", line 97, in main output = model(input_image) File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 719, in forward x = self.transformer(x) # b c h w -> b c h w File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 342, in forward x = attn(x) + x File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 142, in forward attn = attn * dis[None, :, :, :] RuntimeError: The size of tensor a (4096) must match the size of tensor b (1024) at non-singleton dimension 3

Make sure your num_patches is equal to h*w, where h and w are the spatial resolutions of the feature maps that enter the CNNAttention module.

**Comment by Jingbx** [comment]
It may be related to the output feature map resolution of the encoder. This is my test
    model = Setr_ConvFormer(n_channels=1, n_classes=1, imgsize=(512, 512), patch_num=64)
    input3 = torch.randn(1, 1, 512, 512)
// encoder layer output    
torch.Size([1, 16, 512, 512])
torch.Size([1, 32, 256, 256])
torch.Size([1, 64, 128, 128])
torch.Size([1, 128, 64, 64])
// h * w = 64 * 64 == patch_num * patch_num=64 * 64
Input shape: torch.Size([1, 1, 512, 512]) --> Output shape: torch.Size([1, 1, 512, 512])

**Comment by WenLion1** [comment]
Could you please tell me why I still encounter this problem after setting num_patches to num_patches = self.image_height * self.image_width?
![Uploading 1718706909046.jpg…]()

**Comment by WenLion1** [comment]
Could you please tell me why I still encounter this problem after setting num_patches to num_patches = self.image_height * self.image_width?
Traceback (most recent call last):
  File "/root/autodl-tmp/project/ConvFormer-main/train.py", line 132, in <module>
    main()
  File "/root/autodl-tmp/project/ConvFormer-main/train.py", line 97, in main
    output = model(input_image)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/project/ConvFormer-main/models/SETR.py", line 741, in forward
    x = self.transformer(x)  # b c h w -> b c h w
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/project/ConvFormer-main/models/SETR.py", line 363, in forward
    x = attn(x) + x
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/project/ConvFormer-main/models/SETR.py", line 144, in forward
    attn = attn * dis[None, :, :, :]
RuntimeError: The size of tensor a (16) must match the size of tensor b (1024) at non-singleton dimension 3

**Comment by WangYQ999** [comment]
> > Traceback (most recent call last): File "train.py", line 132, in main() File "train.py", line 97, in main output = model(input_image) File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 719, in forward x = self.transformer(x) # b c h w -> b c h w File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 342, in forward x = attn(x) + x File "/home/hdu/anaconda3/envs/wd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/data/jupyter/yww/ConvFormer-main/models/SETR.py", line 142, in forward attn = attn * dis[None, :, :, :] RuntimeError: The size of tensor a (4096) must match the size of tensor b (1024) at non-singleton dimension 3
> 
> Make sure your num_patches is equal to h*w, where h and w are the spatial resolutions of the feature maps that enter the CNNAttention module.

num_patches的作用好像就只是计算了relative_pos_dis，我看其他地方也没有使用，所以relative_pos_dis=h*w?
